version: '3.7'

services:
    app:
        container_name: savings-mate-app
        build:
            context: _docker/local/php-fpm
            dockerfile: Dockerfile
        image: savings-mate-app/php-fpm
        restart: always
        working_dir: /var/www/SavingsMate
        environment:
            - TZ=${TZ-America/Sao_Paulo}
        volumes:
            - .:/var/www/SavingsMate
        depends_on:
            - mongo
        networks:
            - savings_mate_network
        ports:
            - "9000:9000"
            - "9001:9001"
            - "9003:9003"

    mongo:
        container_name: savings-mate-mongo
        image: mongo
        environment:
            MONGO_INITDB_ROOT_USERNAME: '${DB_USERNAME:-user}'
            MONGO_INITDB_ROOT_PASSWORD: '${DB_PASSWORD:-secret}'
        ports:
            - "27017:27017"
        volumes:
            - mongo-data:/data/db
        networks:
            - savings_mate_network

    redis:
        container_name: savings-mate-redis
        image: redis:latest
        restart: always
        command: [ "redis-server", "--requirepass", "${REDIS_PASSWORD:-secret}" ]
        environment:
            REDIS_PASSWORD: '${REDIS_PASSWORD}'
        volumes:
            - 'hw_redis:/data'
        ports:
            - "6379:6379"
        networks:
            - savings_mate_network

networks:
    savings_mate_network:
        driver: bridge

volumes:
    mongo-data:
        driver: local
    hw_redis:
        driver: local
